# Minimal CI-only configuration
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
# Skip network-dependent tests
test_pattern = "CI"
fs_permissions = [{ access = "read", path = "./"}]
verbosity = 3
