# CI configuration for Arbitrum migration
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"

# Test configuration
# Include both CI test and core contract tests
match_path = "test/(CI|PasifikaTreasury|PasifikaMembership|PasifikaMoneyTransfer).t.sol"
test_pattern = "test*"
# Exclude specific problematic tests
no_match_test = "testFinalizeProfit|testProfitSharingState|testMarketplace"

# Allow file operations for tests
fs_permissions = [{ access = "read-write", path = "./"}]
verbosity = 3

# Optimize for Arbitrum
optimizer = true
optimizer_runs = 200
