# Minimal CI-only configuration
[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
# Test configuration
match_path = "test/CI.t.sol"
test_pattern = "test_CI*"
match_contract = "CITest"
fs_permissions = [{ access = "read-write", path = "./"}]
verbosity = 3
