[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
evm_version = "paris"
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
]

[profile.default.foundry.evm]
chain_id = 42161  # Arbitrum Mainnet
version = "paris"

[profile.default.foundry.rpc]
url = "https://arb1.arbitrum.io/rpc"

[profile.default.foundry.etherscan]
key = "${ARBISCAN_API_KEY}"
url = "https://api.arbiscan.io/api"

[profile.rpc-endpoints]
core-mainnet = "https://rpc.coredao.org"
core-testnet = "https://rpc.test2.btcs.network"
arbitrum-mainnet = "https://arb1.arbitrum.io/rpc"
arbitrum-goerli = "https://goerli-rollup.arbitrum.io/rpc"
arbitrum-sepolia = "https://sepolia-rollup.arbitrum.io/rpc"

[profile.ci]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]
optimizer = true
optimizer_runs = 200
verbosity = 3
evm_version = "london"
memory_limit = 2048
test_pattern = "test*.sol"
no_match_test = "testFinalizeProfit|testProfitSharingState"
block_timestamp = 1651990474
block_number = 15000000
gas_limit = 9223372036854775807
initial_balance = "0xffffffffffffffffffffffff"
sender = "0x1804c8AB1F12E6bbf3894d4083f33e07309d1f38"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[fuzz]
runs = 1000
max_test_rejects = 65536
seed = "0x3e8"
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
