[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"

[profile.default.foundry.evm]
chain_id = 80002  # Polygon Amoy Testnet
version = "london"

[profile.default.foundry.rpc]
url = "https://rpc-amoy.polygon.technology/"

[profile.default.foundry.etherscan]
key = "${POLYGONSCAN_API_KEY}"

[profile.rpc-endpoints]
core-mainnet = "https://rpc.coredao.org"
core-testnet = "https://rpc.test2.btcs.network"

[profile.ci]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
ffi = true
fs_permissions = [{ access = "read-write", path = "./" }]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
